//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int student_id { get; set; }
        public string student_ssn { get; set; }
        public string student_username { get; set; }
        public Nullable<int> student_course_occurance_code { get; set; }
    }
}
