//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {

      
     
        public int register_id { get; set; }
        public string register_student_ssn { get; set; }
        public Nullable<int> register_course_occurance_code { get; set; }
        public string register_test_number { get; set; }
        public string register_date { get; set; }
        public string register_grade { get; set; }
        public string register_term { get; set; }
    }
}
