//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int course_id { get; set; }
        public string course_code { get; set; }
        public string course_application_code { get; set; }
        public string course_term { get; set; }
        public string course_student_username { get; set; }
    }
}
